In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import random
from pathlib import Path
import sys
import os

In [ ]:
BASE_DIR = Path.cwd() 
print(BASE_DIR)

c:\Users\Neezy\Videos\attacks_improved_v2\Attacks-Improved_v2\Random_forest

In [ ]:
project_root = os.path.abspath('..')
if project_root not in sys.path: 
    sys.path.append(project_root)

In [ ]:
#### log initialization
from utils.logs import logger_module 
logger = logger_module(logger_name=__name__)

In [ ]:
data = pd.read_csv(BASE_DIR.parent/'data/ds_with_sample_name.csv')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
data.head()

,Sample Name,category,SetErrorMode,OleInitialize,LdrGetDllHandle,LdrLoadDll,LdrGetProcedureAddress,NtOpenSection,NtMapViewOfSection,RegOpenKeyExW,RegQueryValueExW,RegCloseKey,NtClose,NtOpenKey,NtQueryValueKey,GetSystemWindowsDirectoryW,NtCreateFile,NtCreateSection,RegOpenKeyExA,CreateActCtxW,GetSystemDirectoryW,GetVolumeNameForVolumeMountPointW,NtDuplicateObject,LoadStringW,NtCreateMutant,GetNativeSystemInfo,RegEnumKeyW,NtQuerySystemInformation,RegQueryValueExA,NtQueryDirectoryFile,GlobalMemoryStatusEx,CoCreateInstance,NtAllocateVirtualMemory,CreateDirectoryW,DeleteFileW,GetFileSizeEx,NtReadFile,GetFileInformationByHandleEx,GetSystemTimeAsFileTime,GetVolumePathNamesForVolumeNameW,LdrUnloadDll,CoInitializeEx,NtOpenProcess,CoUninitialize,NtFreeVirtualMemory,NtOpenFile,NtQueryInformationFile,GetFileAttributesW,FindFirstFileExW,NtQueryAttributesFile,NtUnmapViewOfSection,SetFilePointerEx,SetFilePointer,GetTempPathW,GetFileSize,NtWriteFile,FindResourceExW,LoadResource,SHGetFolderPathW,NtProtectVirtualMemory,GetFileType,ReadProcessMemory,GetForegroundWindow,GetSystemMetrics,SetFileTime,NtSetInformationFile,SearchPathW,NtOpenMutant,RegEnumKeyExW,DrawTextExW,GetAsyncKeyState,GetDiskFreeSpaceExW,GetKeyState,FindWindowW,FindWindowExA,CreateThread,MoveFileWithProgressW,SetFileAttributesW,RemoveDirectoryW,NtTerminateProcess,CreateToolhelp32Snapshot,Process32FirstW,Process32NextW,FindWindowExW,SetEndOfFile,GetCursorPos,SetUnhandledExceptionFilter,OutputDebugStringA,GetSystemInfo,FindResourceW,SizeofResource,NtDelayExecution,GetKeyboardState,WSAStartup,socket,setsockopt,NtDeviceIoControlFile,closesocket,GetBestInterfaceEx,GetAdaptersAddresses,NtQueryKey,RegCreateKeyExW,GetAddrInfoW,GetUserNameExW,RegSetValueExW,RegDeleteValueW,InternetQueryOptionA,URLDownloadToFileW,IsDebuggerPresent,CreateProcessInternalW,GetTimeZoneInformation,LookupAccountSidW,SendNotifyMessageW,UuidCreate,GetFileVersionInfoSizeW,GetFileVersionInfoW,NtEnumerateValueKey,EnumWindows,OpenSCManagerW,GetComputerNameW,GetUserNameW,NetShareEnum,GetFileInformationByHandle,DeviceIoControl,ShellExecuteExW,RegQueryInfoKeyW,RegEnumValueW,RegDeleteKeyW,NtReadVirtualMemory,NtOpenKeyEx,NtSetValueKey,NtCreateKey,GetVolumePathNameW,GetFileAttributesExW,GetUserNameExA,RegCreateKeyExA,CryptAcquireContextW,NtEnumerateKey,NtDeleteKey,OpenServiceW,NtOpenDirectoryObject,CreateJobObjectW,SetInformationJobObject,RegEnumKeyExA,GetShortPathNameW,LoadStringA,FindResourceA,DrawTextExA,RegQueryInfoKeyA,RegSetValueExA,SHGetSpecialFolderLocation,NtCreateThreadEx,NtResumeThread,gethostbyname,GetSystemDirectoryA,FindResourceExA,GetDiskFreeSpaceW,CertOpenStore,CryptDecodeObjectEx,CertControlStore,CryptHashData,NtOpenThread,MessageBoxTimeoutW,LookupPrivilegeValueW,CryptAcquireContextA,SetFileInformationByHandle,RemoveDirectoryA,SetWindowsHookExW,CopyFileW,GetFileVersionInfoSizeExW,GetFileVersionInfoExW,CoInitializeSecurity,WSASocketW,WSAConnect,UnhookWindowsHookEx,CertOpenSystemStoreW,getaddrinfo,InternetCrackUrlW,CoCreateInstanceEx,CoGetClassObject,IWbemServices_ExecQuery,SetStdHandle,GlobalMemoryStatus,NetGetJoinInformation,CryptCreateHash,GetComputerNameA,InternetOpenA,InternetOpenUrlA,InternetCloseHandle,ReadCabinetState,InternetOpenW,InternetConnectW,HttpOpenRequestW,HttpSendRequestW,NtDeleteValueKey,HttpQueryInfoA,RegEnumValueA,CryptProtectMemory,CreateServiceW,WriteConsoleA,CopyFileA,WriteProcessMemory,SendNotifyMessageA,RegDeleteKeyA,WriteConsoleW,JsGlobalObjectDefaultEvalHelper,ObtainUserAgentString,StartServiceW,NtQueueApcThread,RtlAddVectoredContinueHandler,CryptExportKey,CryptGenKey,CryptEncrypt,NetUserGetInfo,GetUserNameA,InternetOpenUrlW,GetAdaptersInfo,Module32FirstW,NtGetContextThread,Module32NextW,RtlAddVectoredExceptionHandler,NtSuspendThread,OpenSCManagerA,OpenServiceA,NtQueryMultipleValueKey,MessageBoxTimeoutA,ControlService,NtTerminateThread,EncryptMessage,DecryptMessage,DeleteService,FindWindowA,RtlRemoveVectoredExceptionHandler,ioctlsocket,connect,select,SetWindowsHookExA,CreateServiceA,bind,listen,getsockname,accept,InternetCrackUrlA,InternetConnectA,HttpOpenRequestA,HttpSendRequestA,sendto,shutdown,RtlDecompressBuffer,NtSetContextThread,Thread32First,Thread32Next,CreateRemoteThread,InternetReadFile,CreateRemoteThreadEx,timeGetTime,DnsQuery_A,InternetGetConnectedState,RegisterHotKey,CryptDecrypt,CopyFileExW,NtDeleteFile,send,DeleteUrlCacheEntryA,EnumServicesStatusW,recv,NtWriteVirtualMemory,InternetSetOptionA,NtLoadDriver,EnumServicesStatusA,RegDeleteValueA,CertCreateCertificateContext,InternetSetStatusCallback,IWbemServices_ExecMethod,AssignProcessToJobObject,StartServiceA,CryptProtectData,CryptUnprotectData,CryptUnprotectMemory,label
0,4e0d1edb76747fd945b87dd18299298f0df719edbea946...,Ransomware,245,6,141,253,1426,49,64,1547,1308,7834,18734,413,172,58,7398,41,6553,6,25,21,46,243,24,9,8,7,6417,920,1,53,3346,9,12,6,11208,3,192,48,74,34,15,40,3771,65,15,149,17478,14,50,0,51483,1,14,40704,32,31,8,6,406,0,4,670,3317,6,0,1,128,86,0,0,0,0,0,6,3507,7016,0,75,0,0,0,134,3314,0,21,0,10,2,1,6552,0,8,6,6,48,6,4,2,12,235,2,8,271,69,0,0,2,28,1,6,0,2,9,9,0,6,2,15,0,1,0,0,5,72,128,0,0,0,0,0,5,16,0,4,1,0,0,2,7,0,0,90,0,93,0,0,0,4,6,1,4,0,4,0,0,0,0,0,0,8,0,6,2,0,0,0,1,0,0,8,0,0,0,0,0,4,8,10,4,0,2,0,0,2,3,2,7,0,0,0,0,0,0,0,0,4,0,2,0,3,0,0,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36,1
1,GandCrab.exe,Ransomware,2,0,11,2,24,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22299,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,jigsaw,Ransomware,1603,1,200,70,564,2,524,195,317,136,1977,18,45,10,1213,524,4,5,11,3,9,5,6,1,0,4,0,338,13,0,829,3,214,0,459,0,39,8,7,4,4,0,291,146,748,25,0,6,519,0,0,0,759,351,1,0,11,122,848,0,0,6,0,0,276,2,38,0,0,0,0,0,0,7,0,0,0,3,0,0,0,0,0,0,3,0,162,0,0,6,0,0,0,0,0,0,0,0,45,2,0,0,1,0,0,0,2,1,2,0,0,1,0,0,318,0,0,0,0,0,0,1,1,12,10,0,0,38,1,3,0,240,0,0,213,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,651,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,EternalRocks,Ransomware,1078,1,70,32,245,4,14,106,182,66,134,7,7,2,95,14,2,3,4,0,7,4,14,0,0,2,0,17,13,0,610,4,0,0,1118,0,102,0,2,4,3,0,374,19,0,11,0,5,3,0,1309,0,8,2244,0,0,2,88,150,0,0,1,0,0,0,2,21,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,1,0,92,0,0,237,0,1,0,2,0,2,0,0,4,1,0,0,0,0,0,0,1,0,3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,6,5,0,0,5,0,0,0,447,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,BlackRose_8fec485e47fd1231aeb1a4107a4918f92c2b...,Ransomware,2,0,0,3,5,0,2,0,0,1,51,41,8,0,2,2,0,0,1,0,0,2,2,0,0,0,0,5,0,0,6,0,0,0,1,0,5,0,2,0,0,1,3,5,1,1,0,0,4,0,1,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,2,0,2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [ ]:
data.shape

(2913, 280)

In [ ]:
X = data.iloc[:, 2:-1].values
y = data.iloc[:, -1].values
original_indices = np.arange(len(X)) 
X_train, X_test, y_train, y_test, idx_train, idx_test = train_test_split(X, y, original_indices, test_size=0.2, random_state=42)
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n {cm}") 
cr = classification_report(y_test, y_pred)
print(f"Classification report:\n {cr}")

Accuracy: 97.60%
Confusion Matrix:
 [[104  13]
 [  1 465]]
Classification report:
               precision    recall  f1-score   support

           0       0.99      0.89      0.94       117
           1       0.97      1.00      0.99       466

    accuracy                           0.98       583
   macro avg       0.98      0.94      0.96       583
weighted avg       0.98      0.98      0.98       583

In [ ]:
original_indices

array([   0,    1,    2, ..., 2910, 2911, 2912], shape=(2913,))

In [ ]:
y_test.shape

(583,)

In [ ]:
def make_pred(sample): 
    single_pred = classifier.predict([sample])
    return single_pred

In [ ]:
ransomware_training_sample_indices = np.where(y_train==1)
idx = np.random.choice(ransomware_training_sample_indices[0], 580, replace=False)
xtrain_poison_candidates = X_train[idx]

In [ ]:
#print(idx)

In [ ]:
#orig_idx = idx_train[idx]

In [ ]:
#data.iloc[orig_idx]

In [ ]:
def make_initial_adversarial(sampled_row,perturbation):
    lst = sampled_row.tolist().copy() #removed [0]
    logger.info(f"initial sample: {lst}") 
    adv_indices = [i for i, x in enumerate(lst) if x == 0] # Track Indices
    logger.info(f"Identified features to perturb: {len(adv_indices)}") 

    adversarial_sample = list(map(lambda x: x+perturbation if x==0 else x, lst))
    logger.info(f"perturbed sample: {adversarial_sample}")
    prediction = make_pred(adversarial_sample) 
        
    if prediction == 0: 
        logger.info("Initial perturbation successful") 
        return adversarial_sample, adv_indices
    else: 
        logger.info("perturbation failed")
        return None, None

def decrement_list(lst, perturbation, adversarial_indices):
    lst2 = lst.copy()
    final_adv_indices = [] # find all the features that have been perturbed.  
    logger.info(f"Identified indices to check if perturbation was necessary: {len(adversarial_indices)}")
    
    for j in adversarial_indices: 
        lst2[j] -= perturbation 
        check_pred = make_pred(lst2) 
        if check_pred != 0:
            lst2[j] += perturbation
            final_adv_indices.append(j)  
    
    logger.info(f"{len(adversarial_indices) - len(final_adv_indices)} features were identified as uneccessary to perturb: features to be optimized: {len(final_adv_indices)} features")        
    
    logger.info(f"Semi Optimized sample: {lst2}")
    return lst2, final_adv_indices ## Return final indices

def optimize(sample, final_adversarial_sample,final_adv_indices): 
                
    logger.info(f"final adversarial indices to check: {len(final_adv_indices)}")
    for j in final_adv_indices: ## trace all the features that removing the perturbation caused incorrect prediction
        while final_adversarial_sample[j]>sample[j]: 
            final_adversarial_sample[j] -= 1
            if make_pred(final_adversarial_sample) == 1: 
                final_adversarial_sample[j] +=1
                break
                
                    
    logger.info(f"Final Adversarial sample: {final_adversarial_sample} ")
    return final_adversarial_sample

In [ ]:
def poison(perturbation): 
    samples = xtrain_poison_candidates
    adversarial_samples = []
    l2_distances = []
    successful_idx = []
    for i, sample in enumerate(samples):  
        adv, adversarial_indices = make_initial_adversarial(sample,perturbation)
        if adv is not None:
           adversarial_sample, final_adv_indices = decrement_list(adv, perturbation, adversarial_indices)
           final_adversarial_sample = optimize(sample, adversarial_sample,final_adv_indices)
           l2 = np.linalg.norm(final_adversarial_sample-sample)
           logger.info(f"l2 distance: {l2}")
           l2_distances.append(float(l2))
           successful_idx.append(idx[i]) 
           adversarial_samples.append(final_adversarial_sample)      
           logger.info(f"sample number: {i}/{len(samples)} complete")
        
    return adversarial_samples, successful_idx

perturbation=70
asamples, adv_idx = poison(perturbation)

In [ ]:
len(asamples)

338

In [ ]:
adv_idx

[np.int64(657),
 np.int64(750),
 np.int64(934),
 np.int64(535),
 np.int64(1825),
 np.int64(481),
 np.int64(812),
 np.int64(360),
 np.int64(1833),
 np.int64(2304),
 np.int64(171),
 np.int64(1783),
 np.int64(1247),
 np.int64(250),
 np.int64(1224),
 np.int64(1183),
 np.int64(2035),
 np.int64(1020),
 np.int64(659),
 np.int64(1865),
 np.int64(955),
 np.int64(253),
 np.int64(2179),
 np.int64(14),
 np.int64(2160),
 np.int64(371),
 np.int64(968),
 np.int64(1672),
 np.int64(1549),
 np.int64(540),
 np.int64(203),
 np.int64(718),
 np.int64(117),
 np.int64(894),
 np.int64(1219),
 np.int64(1401),
 np.int64(523),
 np.int64(1970),
 np.int64(1193),
 np.int64(1235),
 np.int64(2245),
 np.int64(209),
 np.int64(1996),
 np.int64(327),
 np.int64(753),
 np.int64(368),
 np.int64(1586),
 np.int64(637),
 np.int64(77),
 np.int64(1530),
 np.int64(1434),
 np.int64(1662),
 np.int64(1686),
 np.int64(115),
 np.int64(829),
 np.int64(780),
 np.int64(1775),
 np.int64(1927),
 np.int64(1052),
 np.int64(1930),
 np.int64(451),
 np.int64(2256),
 np.int64(1164),
 np.int64(1088),
 np.int64(747),
 np.int64(1685),
 np.int64(537),
 np.int64(980),
 np.int64(1954),
 np.int64(1008),
 np.int64(200),
 np.int64(1889),
 np.int64(1392),
 np.int64(2021),
 np.int64(2036),
 np.int64(273),
 np.int64(1945),
 np.int64(521),
 np.int64(1609),
 np.int64(1058),
 np.int64(1458),
 np.int64(1750),
 np.int64(2274),
 np.int64(5),
 np.int64(723),
 np.int64(1645),
 np.int64(864),
 np.int64(36),
 np.int64(216),
 np.int64(1801),
 np.int64(1461),
 np.int64(2273),
 np.int64(1599),
 np.int64(2213),
 np.int64(1574),
 np.int64(382),
 np.int64(2254),
 np.int64(1680),
 np.int64(1398),
 np.int64(1501),
 np.int64(1719),
 np.int64(1295),
 np.int64(559),
 np.int64(1306),
 np.int64(1169),
 np.int64(1823),
 np.int64(1898),
 np.int64(1810),
 np.int64(1378),
 np.int64(609),
 np.int64(263),
 np.int64(1950),
 np.int64(1845),
 np.int64(719),
 np.int64(1015),
 np.int64(945),
 np.int64(1166),
 np.int64(643),
 np.int64(798),
 np.int64(1933),
 np.int64(969),
 np.int64(1920),
 np.int64(2315),
 np.int64(2326),
 np.int64(1544),
 np.int64(1179),
 np.int64(1114),
 np.int64(1555),
 np.int64(290),
 np.int64(786),
 np.int64(1736),
 np.int64(1516),
 np.int64(1197),
 np.int64(195),
 np.int64(1528),
 np.int64(326),
 np.int64(1844),
 np.int64(419),
 np.int64(670),
 np.int64(2140),
 np.int64(752),
 np.int64(1993),
 np.int64(1634),
 np.int64(2264),
 np.int64(694),
 np.int64(888),
 np.int64(422),
 np.int64(2053),
 np.int64(791),
 np.int64(1819),
 np.int64(963),
 np.int64(1511),
 np.int64(2212),
 np.int64(982),
 np.int64(844),
 np.int64(1906),
 np.int64(1679),
 np.int64(2081),
 np.int64(1475),
 np.int64(161),
 np.int64(1948),
 np.int64(2216),
 np.int64(850),
 np.int64(646),
 np.int64(1189),
 np.int64(65),
 np.int64(620),
 np.int64(343),
 np.int64(40),
 np.int64(1754),
 np.int64(1104),
 np.int64(1087),
 np.int64(656),
 np.int64(732),
 np.int64(1891),
 np.int64(1094),
 np.int64(2206),
 np.int64(365),
 np.int64(1677),
 np.int64(536),
 np.int64(1702),
 np.int64(712),
 np.int64(1307),
 np.int64(1499),
 np.int64(176),
 np.int64(30),
 np.int64(2323),
 np.int64(463),
 np.int64(339),
 np.int64(1943),
 np.int64(1313),
 np.int64(2159),
 np.int64(1955),
 np.int64(387),
 np.int64(1443),
 np.int64(1391),
 np.int64(363),
 np.int64(181),
 np.int64(782),
 np.int64(1057),
 np.int64(745),
 np.int64(223),
 np.int64(188),
 np.int64(1573),
 np.int64(81),
 np.int64(1175),
 np.int64(1383),
 np.int64(1498),
 np.int64(2041),
 np.int64(564),
 np.int64(56),
 np.int64(2045),
 np.int64(386),
 np.int64(988),
 np.int64(341),
 np.int64(2306),
 np.int64(634),
 np.int64(1742),
 np.int64(2063),
 np.int64(2192),
 np.int64(1789),
 np.int64(214),
 np.int64(1199),
 np.int64(111),
 np.int64(1269),
 np.int64(440),
 np.int64(140),
 np.int64(1387),
 np.int64(1274),
 np.int64(1936),
 np.int64(547),
 np.int64(627),
 np.int64(147),
 np.int64(228),
 np.int64(1206),
 np.int64(1331),
 np.int64(603),
 np.int64(303),
 np.int64(433),
 np.int64(45),
 np.int64(1229),
 np.int64(1381),
 np.int64(1507),
 np.int64(311),
 np.int64(1379),
 np.int64(2178),
 np.int64(190),
 np.int64(1138),
 np.int64(881),
 np.int64(1669),
 np.int64(1811),
 np.int64(24),
 np.int64(1874),
 np.int64(834),
 np.int64(518),
 np.int64(930),
 np.int64(1738),
 np.int64(1803),
 np.int64(330),
 np.int64(2050),
 np.int64(127),
 np.int64(1442),
 np.int64(1069),
 np.int64(460),
 np.int64(1922),
 np.int64(1644),
 np.int64(853),
 np.int64(132),
 np.int64(1181),
 np.int64(233),
 np.int64(1268),
 np.int64(1341),
 np.int64(1850),
 np.int64(1366),
 np.int64(2248),
 np.int64(756),
 np.int64(1940),
 np.int64(252),
 np.int64(306),
 np.int64(731),
 np.int64(123),
 np.int64(1552),
 np.int64(1368),
 np.int64(713),
 np.int64(979),
 np.int64(2107),
 np.int64(120),
 np.int64(1787),
 np.int64(1481),
 np.int64(2319),
 np.int64(1297),
 np.int64(265),
 np.int64(606),
 np.int64(174),
 np.int64(2037),
 np.int64(613),
 np.int64(813),
 np.int64(435),
 np.int64(1223),
 np.int64(1913),
 np.int64(1904),
 np.int64(2079),
 np.int64(1125),
 np.int64(1923),
 np.int64(1782),
 np.int64(390),
 np.int64(1320),
 np.int64(2030),
 np.int64(210),
 np.int64(776),
 np.int64(543),
 np.int64(182),
 np.int64(2233),
 np.int64(323),
 np.int64(1864),
 np.int64(578),
 np.int64(765),
 np.int64(1023),
 np.int64(569),
 np.int64(437),
 np.int64(474),
 np.int64(1465),
 np.int64(1163),
 np.int64(1227),
 np.int64(1705),
 np.int64(960),
 np.int64(1878),
 np.int64(158),
 np.int64(154),
 np.int64(677),
 np.int64(1009),
 np.int64(1141),
 np.int64(1284),
 np.int64(482),
 np.int64(1553),
 np.int64(1629),
 np.int64(769),
 np.int64(61)]

In [ ]:
orig_idx = idx_train[idx]

print(orig_idx)

[1724  886   91  628 2527  922 2428 2499 1043 1582 2326  747  482 2407
 2617  981 2616 2342  404 1245 2890 2865 1876  776 2406 2721 1834 1104
  913 1023 1191 2625  868 1928 2680   11 2500 2176 1168  684 2412  873
 1260 2093 1717 1133 1683  488 2190 2050 1063 1961 2863 2262 2684 2034
  548 2750 1818 2854  768  405 1193  779 2443 2264 1611 1556 2888    5
  643 1775 1827 1670 1170 1577 1079 2772 2636 1927 2137 2470   15 2083
 2541 1750 1653   27 2778 2210  561 2394 1762 2692 1967 2509 2042 1830
  830 1972 1640 2353 2654 2547 2317 2032  980  631 2601 1633 2422 2755
  574 1583 2120  817 2057  929  550 1185 2780  959  639  920 2670 2491
 2029 1935  615 1198 2299  587  933 2556 1558 1751 2189 1247 2663 1659
 1563 1843  795 1099 2905   64  454 1765 2903  775   60  804  999  538
 1105 2859  638 2437  455 1733  517  578 2260 2438 1778  591 1052 2522
  887 1614   86 1942  396   18 1092 2402 2736 2041 1880 1234 2352 1982
  728 2597 2691  590 1064 1934 1806 2062 1984 1201  686 2579  579  635
 2113 1587  865 2726 2391 1095 2629 1667 2288 1654 2851   84 2677 2513
  467 2898  632 2706 1911 1944 2774 2154  613  675 1543 2767 2112 2776
 2460  876 1012 1070 2891 2017  702 1265  799  593  738 2630 1884 2621
  395 1567 2165  909  645 1150 2146  541 2803 1565 2221 1803  703 1681
  475 2393 2177 2147 1619 2528 2148  681  762  502  623  398 2739 1695
 1009  924  921 1966 1980 1038 2345 2795  898    7 1929 1908 1774 1710
 1001  754  945 1214 2063   14 2910  687   58  497  763 2555  534 2265
 2539 1622 1761 1080 1759 2660 2559 1109 1668 1192 2837    9 1576 1707
 1822 1145 2742 1688 2494  438 2605  466 2419   41  726  925 2844 1595
  682 1648 1065 1124 2675   71   50  891 1851 1177 1727 2144 2475 2070
 2809   59 1808 2319 2885 2900 2046 1646 1557   13 2347   55 2211 1676
 1666 1184 1866  549 2358 1758 2635 1606 1566 1078 1126 2784 1061 2413
 2036  680   21  491 1172  586  571 1020 1747 1165 1540 2552 2561 2403
  459  490 2043 2359 2699 1737 2131  935  815   46 1148 1216 1050 1989
 1536  646  941    0  582  722 1157 1087  472  494 2550  889 2392 2232
  979 1169 1120 1581  946 2023 2483 2729 1785  719 2133 2870 2538  884
 2415 1243  496 2607 1926  826   39 1699 2497 1055  820 2832 1232  942
 2284  441 2420  740 2322  704  731 2025  809  835 2090  657 1730 2252
 2842 1008 1623 2089  793 1796 1115  766 1943  409  556  616 2179 2439
  878 2852 1219 1756    4 1799  788 2224 2502 1767  425  755 1182 1197
  558 2257 2153  864 1865 1277 2118  855 2280   83 2511 2569 2643 2149
  951 2285 2886 2135 1013  406 1289 1290 1255  451 1100 2287 2487 1607
 2700 1867 2424 1713 2266 2270  512  580 2835 1108 1945 2685  854 2207
  499 1586 2477  514 2085 2474 1917 1274 2834  611 1833 2695 1575 2722
 2718 1735 2104 1924 2302 2717 2055 2581 1893 1914   52 2773 2183 1741
 2458  966  708 2442  515  833  649 1118 1188  440  715 2797 1231 2095
  758 2848  505 1919 1985 1957 1909 2788 2506 1682 2876 1130 2364 1199
 2075 1705 1019 2757  426 2365]

In [ ]:
data.iloc[orig_idx]

                                            Sample Name    category  \
1724  Dharma_90c54543aaf085e00879d4fe98a6dfb8148548f...  Ransomware
886   Egregor_2d01c32d51e4bbb986255e402da4624a61b8ae...  Ransomware
91    DoejoCrypt_10bce0ff6597f347c3cca8363b7c81a8bff...  Ransomware
628   Thanos_ae66e009e16f0fad3b70ad20801f48f2edb904f...  Ransomware
2527                                 UpdateForm147.html  Ransomware
922   GandCrab_9b908b006d12e553d636e69e54ee1bbdf6301...  Ransomware
2428                             UpdateInformation.html  Ransomware
2499                             UpdateInformation.html  Ransomware
1043  NanoCore_83fe1c4a70de34edbc70f7a3e2c920c222fdf...  Ransomware
1582  Babuk_393a7a313548a4edc025fb47c6c8e614ecc2b41d...  Ransomware
2326                                 UpdateRecords.html  Ransomware
747   Azov_7dbc20189cc8306f3d446636e71b53e0663bc9ee3...  Ransomware
482   GandCrab_759284272f3abbf46b9464e6484f60b808f19...  Ransomware
2407                                     UpdateNow.html  Ransomware
2617                                 Attachment402.html  Ransomware
981   Kraken_b639e26a0f0354515870ee167ae46fdd9698c2f...  Ransomware
2616                                 UpdateForm245.html  Ransomware
2342                                 UpdateForm748.html  Ransomware
404   Zeppelin_f247ae6db52989c9a598c3c7fbc1ae2db54f5...  Ransomware
1245  VirLock_a9016bf1ef3af8f208aa93b840329a4cd646af...  Ransomware
2890  WannaCry_8f86b42241e81b7461ba45fde82505332e457...  Ransomware
2865  Venus_0a4e5832841ffff9f8d27ce8216d655c8743b682...  Ransomware
1876  Hive_efdbfcb717b109b816e2d2f99c0d923803c70dd08...  Ransomware
776   BlackBasta_350ba7fca67721c74385faff083914ecdd6...  Ransomware
2406                             UpdateInformation.html  Ransomware
2721                                  FormAttached.html  Ransomware
1834  GandCrab_e7b605aaf4556e3626fd05dffabbf77378807...  Ransomware
1104  Petya_4c1dc737915d76b7ce579abddaba74ead6fdb5b5...  Ransomware
913   Formbook_421af5adde9ca3fd3312067c0a113faaef07a...  Ransomware
1023  Mespinoza_4770a0447ebc83a36e590da8d01ff4a418d5...  Ransomware
1191  ShinoLocker_495d9eca1e009ecdd97618f096da1d8407...  Ransomware
2625                                    Attachment.html  Ransomware
868   Cyborg_ce7a28d3f7cbcb06f484a17dcd244ac1cd126f8...  Ransomware
1928  Nitro_54b1bae540a9329522f51dac880b4970103a048a...  Ransomware
2680                                 UpdateForm101.html  Ransomware
11    Babuk_6103e26f6f9d5fd895d9c06e1f5e141ce74d8ebd...  Ransomware
2500                                          FORM.html  Ransomware
2176  None_aa9edd5569fc2940680fdec96cbeddd523ffe907a...  Ransomware
1168  RSJon_e836a71f9df0e8f4f6b5920ec0a1e311cb8933d7...  Ransomware
684   ArkeiStealer_3edbea6a51777aa0f851e4df845fe7432...  Ransomware
2412                             UpdateInformation.html  Ransomware
873   Dridex_0457768f9d8d70ff59275c27bc99d45c1c48cf1...  Ransomware
1260  Vovabol_dd9f9ce3b45500ca095a888b4b2300f0efeed9...  Ransomware
2093  None_5e8bb9cf9da6b05a04a2a65749931534c55992715...  Ransomware
1717  Dharma_53cee5760768d57218ccc210948592f29d41b98...  Ransomware
1133  RagnarLocker_30dcc7a8ae98e52ee5547379048ca1fc9...  Ransomware
1683  DarkSide_61ca175c2f04cb5279f8507e69385577cf04e...  Ransomware
488   HANTA_13449fb24d735a4847dd174860b5a6cd033c11d8...  Ransomware
2190  None_cd1bb0b84729b272e28a48cdfc22ef1f2577e4a17...  Ransomware
2050  None_2ce119bcf7269076012cf7f06397053f833aa608e...  Ransomware
1063  njrat_3424a8c9c995896f9d6fe3bb4a164d0d8675a781...  Ransomware
1961  NominatusStorm_47913d758d8c6e8395192eaf6928cbe...  Ransomware
2863                           unknown_smb-_amx9zoe.bin  Ransomware
2262                                    PP-Form610.html  Ransomware
2684                                  FormAttached.html  Ransomware
2034  None_1899ff66b76a3f6302fea0afbc26c8452949345d2...  Ransomware
548   None_92190c9789485a0d96bced7040080f0ae35c02898...  Ransomware
2750                                      Attached.html  Ransomware
1818  GandCrab_c32da09050ff997ab98b7837c48351ee384eb...  Ransomware
2854  Stop_970a7f3a8e1caf695dff4a62f2c9da51289f3eea0...  Ransomware
768   BadRabbit_8ebc97e05c8e1073bda2efb6f4d00ad7e789...  Ransomware
405   Zeppelin_39016358b939b83cf9997c447458ae2d13186...  Ransomware
1193  Snatch_1d67abe1ec08e6215e08d6bb595ade3d1d33d0e...  Ransomware
779   BlackBasta_c4c8be0c939e4c24e11bad90549e3951b79...  Ransomware
2443                                  FormAttached.html  Ransomware
2264                                 UpdateForm252.html  Ransomware
1611  Chaos_31c783b0211bf4b72f10b6dac6f933b7aba570ff...  Ransomware
1556  Azov_89566f5dbdc136845cba15979fb9f7184f59385ce...  Ransomware
2888  WannaCry_7aebbcd75ea79673da63fee5f95805aa0ca8e...  Ransomware
5     Balaclava_5de4af86a4410fb6a4c7d54ba4586d35b6ab...  Ransomware
643   Vipasana_e49778d20a2f9b1f8b00ddd24b6bcee81af38...  Ransomware
1775  GandCrab_6e1eaa6ded8689f1956ee9725f7040cfbd348...  Ransomware
1827  GandCrab_d4c3d2730f423f7dc22db5b23812d83c3df7d...  Ransomware
1670  DarkSide_029c5d48e425206e2ae84a63d62bdbc803627...  Ransomware
1170  RubberDucky_bdcbc119335bda8a8d875c7e8029e1a587...  Ransomware
1577  Azov_febdd0a7b6040ba8ebe0d2bbaf9c832bfe32c2491...  Ransomware
1079  NominatusStorm_bd9023c7ffe3374bd4fb294c66c6b0e...  Ransomware
2772  RedLineStealer_18e1994bf2f3d308c028a13a0bf7de3...  Ransomware
2636                             UpdateInformation.html  Ransomware
1927  Nitro_43bb3267bbce92106b2699d236d66c4fdd549446...  Ransomware
2137  None_95fbc96ce7e1ceddccb0ef282a0143cc37fb3eb23...  Ransomware
2470                                    FormUpdate.html  Ransomware
15    Babuk_f1719415abe4dcba0daef0a1e5c8994d1d3c0c65...  Ransomware
2083  None_56990b801d101923eb89cf71604e9af32d7ce8d07...  Ransomware
2541                                    FormUpdate.html  Ransomware
1750  GandCrab_2f2b32dc3a33be515a8d3250dae180cd9a7a5...  Ransomware
1653  Conti_39b74b2fb057e8c78a2ba6639cf3d58ae91685e6...  Ransomware
27    MountLocker_e435a95489a4ebdfdc12031091f92a7f9c...  Ransomware
2778  RedLineStealer_27337c551cdbb0bdf09a646f445f240...  Ransomware
2210  None_d620778dbbcf11e3a293aeaaebac7b6a9a02e7d87...  Ransomware
561   Phobos_f0aec57001a184ea82122a59c6e5be48042f75d...  Ransomware
2394                                 UpdateForm990.html  Ransomware
1762  GandCrab_544b8a467254029146494bb96bc0a32e2d9b0...  Ransomware
2692                                    UpdateForm.html  Ransomware
1967  NominatusStorm_60b456372f9f970fdf8e5a544b914aa...  Ransomware
2509                                    Attachment.html  Ransomware
2042  None_1fda7a2eeb2478c97b59f75f094c546d585923b28...  Ransomware
1830  GandCrab_e0edd00203acc80dfeb3121dfe150c1fa5cbc...  Ransomware
830   ChupaCabra_c82ecb3d5e3987a98b7ad91beaa73800669...  Ransomware
1972  NominatusStorm_7112a45ea2f6672b908d3e74967448d...  Ransomware
1640  Chaos_db0759eb584acd22fc6594ff7b8f6dffed34fb9e...  Ransomware
2353                                      Attached.html  Ransomware
2654                                    Attachment.html  Ransomware
2547                                 UpdateRecords.html  Ransomware
2317                                          FORM.html  Ransomware
2032  None_17e50f14e1c106d9a6495cbf84e9ebca510b049de...  Ransomware
980   LimeRAT_297dbbb1daca4b23893b034ab20b8afd0de766...  Ransomware
631   Troldesh_4dce2a774b73176b76f6732f88c66ca6c80b3...  Ransomware
2601                                     Update229.html  Ransomware
1633  Chaos_b097dca0abb2ca95a51eb2edc8b124007c736568...  Ransomware
2422                                     Update425.html  Ransomware
2755                                    Attachment.html  Ransomware
574   Ryuk_92f124ea5217f3fe5cbab1c37a961df0437d5a9cb...  Ransomware
1583  Babuk_00fdeee2f48cc21a5b3da49aacda35513a98d671...  Ransomware
2120  None_7ed29b5971fdfce885116395debc7289bf0e27966...  Ransomware
817   BlueSky_b5b105751a2bf965a6b78eeff100fe4c75282a...  Ransomware
2057  None_2ede659bfffeadc8b93ce25d93e3eabe8d792512b...  Ransomware
929   Generic Trojan_fa73963e516d9be0cc8ae60d7a1cd8b...  Ransomware
550   None_ea7ed9bb14a7bda590cf3ff81c8c37703a028c4fd...  Ransomware
1185  Seven_000ec059ab4eaefd2591449c6581b34748d3f90e...  Ransomware
2780  RedLineStealer_48586ad6d444978aac4736f05bef275...  Ransomware
959   Hive_4d7e2b3eeb7958a60f9ac7a572cb2c560504f11db...  Ransomware
639   ViraLock_f4b11885a3056fc56efdedbc0dd71fae15236...  Ransomware
920   GandCrab_5d50191678dabdc76355a6ed55862d6847b63...  Ransomware
2670                                  FormAttached.html  Ransomware
2491                                      Attached.html  Ransomware
2029  None_1667e1635736f2b2ba9727457f995a67201ddcd81...  Ransomware
1935  Nitro_7e3fb87027b84b39e369efde5f180e6d0bcfda15...  Ransomware
615   Suncrypt_3f6e996ee4a40d2d19b648669d91465626273...  Ransomware
1198  Snake_e5262db186c97bbe533f0a674b08ecdafa3798ea...  Ransomware
2299                             UpdateInformation.html  Ransomware
587   Snake_edef8b955468236c6323e9019abb10c324c27b4f...  Ransomware
933   Geodo_f538719127d85b063afe7fcd398cdeef76750ae2...  Ransomware
2556                                FormAttachment.html  Ransomware
1558  Azov_96d611a756a0f35f1009cfa2f9527bbd3007099d6...  Ransomware
1751  GandCrab_37e0071eaa1281a0521879ca7ffb2668207fb...  Ransomware
2189  None_c3c50adcc0a5cd2b39677f17fb5f2efca52cc4e47...  Ransomware
1247  Voidcrypt_c1819043839dddcca0b5de3d438cffb67c79...  Ransomware
2663                                 UpdateForm366.html  Ransomware
1659  Conti_7f6421cdf6355edfdcbddadd26bcdfbf984def30...  Ransomware
1563  Azov_a7aed9c1c1457819089845f21f73c66e8a35528cc...  Ransomware
1843  GandCrab_f66765eb288768d6ff922737b6f840fd18730...  Ransomware
795   Blackcocaine_41f533f7b8f83e5f0d67e90c7b38d1fdc...  Ransomware
1099  PENTA_655707f033b1b4f563617925a7e8cac298eb790a...  Ransomware
2905                       Win32.SpyBot_make spybot.bat  Ransomware
64    HDLocker_b74d0a068b387f7569f9a42729853e742a99c...  Ransomware
454   Dharma_553532c3bc00e3b85bcbac054bc4f05cb4fffba...  Ransomware
1765  GandCrab_56d931f3b69d702f4a6244057d3c234091bd2...  Ransomware
2903                               Win32.RxBot_rBot.plg  Ransomware
775   BlackBasta_0d6c3de5aebbbe85939d7588150edf7b7bd...  Ransomware
60    CryLock_03014ebd23ea5748d944cadd8b2ab3001fea71...  Ransomware
804   BlackKingdom_63d6c419a8229bc7fc2089a2899d27bac...  Ransomware
999   Magniber_9095bbb4b123a353a856634166f193124bdc4...  Ransomware
538   Nemty_006c9ba4ca0218e7bd2c7c21653497d3215bbeef...  Ransomware
1105  PenterWare_f97868b93747008b2b67f509958fa5e7d3d...  Ransomware
2859  Stop_fbdb067707c1c1338e177f6e0a0aa27b926079d70...  Ransomware
638   Vipasana_c0cf40b8830d666a24bdd4febdc162e95aa30...  Ransomware
2437                                 Attachment742.html  Ransomware
455   Dharma_a08c192df62e58faf203a10d830a6f0c34f1d84...  Ransomware
1733  GandCrab_05f7b5de8b675a6dc828fa0d81c8ce730064f...  Ransomware
517   Mespinoza_6f4338a7a3ef8e491279ae81543a08554cad...  Ransomware
578   Ryuk_d7333223dcc1002aae04e25e31d8c297efa791a2c...  Ransomware
2260                             UpdateInformation.html  Ransomware
2438                                    FormUpdate.html  Ransomware
1778  GandCrab_7cbbcf2bcfd13d2187f3fd31080d7ba64c9b3...  Ransomware
591   Snatch_2339489be44f93b61688ee3b65d0bd2fede5f6d...  Ransomware
1052  NightSky_ff5757086c464d624f4a6674d65409fb6fa84...  Ransomware
2522                                FormAttachment.html  Ransomware
887   Egregor_3b13b6f1d7cd14dc4a097a12e2e505c0a4cff4...  Ransomware
1614  Chaos_51aaa701c5e863deb066216a2f80d6efd4eb909d...  Ransomware
86    None_ee06c557f1acd5c4948b1df0413e49f3885f8ac96...  Ransomware
1942  NominatusStorm_11cc75fcea761e53c1a49a7b177b39a...  Ransomware
396                           Wannacry_smb-kmnr7qja.bin  Ransomware
18                                    Katyusha_katyusha  Ransomware
1092                                   Other_muddyc3.py  Ransomware
2402                                    UpdateForm.html  Ransomware
2736                                    Attachment.html  Ransomware
2041  None_2198326706d69898ad35ea53a7fab21ef36120923...  Ransomware
1880  Hive_c931c14c4932cb7155bd9b6d5afc29a244f98a25f...  Ransomware
1234       trickbot_Sample_5f6b5cda69480900164d7b49.bin  Ransomware
2352                                FormAttachment.html  Ransomware
1982  NominatusStorm_a6fc68cdf1d20582d8bfb46b0e234fe...  Ransomware
728   ARCrypter_5634e4e97a71930c574b80e50ee479ab782b...  Ransomware
2597                             UpdateInformation.html  Ransomware
2691                             UpdateInformation.html  Ransomware
590   Snatch_9b1ee7e79dee8df07307a1be4899fc076a02aac...  Ransomware
1064  njrat_51be3d6849f94382fbb2e238aa0536ce498546c6...  Ransomware
1934  Nitro_6695641abf1570268dcfcc3728d35eff3857c1b5...  Ransomware
1806  GandCrab_ac8508ee470a60e9db4435d2b3942b9abc79d...  Ransomware
2062  None_32708c5d376f130b48bf3bd706879c1945a2d7010...  Ransomware
1984  NominatusStorm_a22c8c9fd79b57f4242f7aea561c220...  Ransomware
1201  SoranoStealer_63749db0a9eb1a3c20cbeed08aae309e...  Ransomware
686   ArkeiStealer_744ec52f480cb86b7e84fbbfe4b1880f5...  Ransomware
2579                                 UpdateForm116.html  Ransomware
579   Ryuk_781bc4dcbd459893397a8b987bf697f5b95435dfa...  Ransomware
635   UIWIX_146581f0b3fbe00026ee3ebe68797b0e57f39d1d...  Ransomware
2113  None_7886ceadafacdaaa0118c8412eda7b48db1f65f79...  Ransomware
1587  Babuk_ab8eee432fa636360b3c6724fe6851e9cf8eeae1...  Ransomware
865   DeriaLock_689e2a3a5422785df87baf016ee8c820ee0d...  Ransomware
2726                                      Attached.html  Ransomware
2391                                       Form679.html  Ransomware
1095  Payme_4410111ba794c46861f4fbfce06d6c8a790582d0...  Ransomware
2629                               AttachedForm629.html  Ransomware
1667  Conti_d6386b2747335f7b0d13b1f69d995944ad8e9b71...  Ransomware
2288                             UpdateInformation.html  Ransomware
1654  Conti_6941ae541692b03f44f81bd5517e0ff225e2a57a...  Ransomware
2851  Stop_96c89c88b564285109b05c3ee26f2568a08b3d14f...  Ransomware
84                                          Locky_Locky  Ransomware
2677                                    UpdateForm.html  Ransomware
2513                               AttachedForm362.html  Ransomware
467   Egregor_9017c070ad6ac9ac52e361286b3ff24a315f72...  Ransomware
2898  WannaCry_fb906531e1ea9546e4df878394a50b9e67920...  Ransomware
632   Troldesh_29d48c4dfebf4aba654910a59de5a66e43caa...  Ransomware
2706                                  FormAttached.html  Ransomware
1911  Magniber_780fbd29b8d2e4d51905608259d3876492a31...  Ransomware
1944  njrat_b4f86ff48c5f6b01e0ad4543fb78e0435e81f3ec...  Ransomware
2774  RedLineStealer_114e3769d9cff47038ef22c3827dc28...  Ransomware
2154  None_9df293040109f3da3fe4e8ec398587dd03b1d38bf...  Ransomware
613   Stop_b055016e0d82c57b58cd126f26b4b8f4dae1441f0...  Ransomware
675   GlobeImposter_750984dff0d13260e17e9bb1a3482f1b...  Ransomware
1543  Azov_5f474dcb05e85047169732183a9085a767c995d5f...  Ransomware
2767  RedLineStealer_0a00b6668696bf62e14ea1acaa85539...  Ransomware
2112  None_7860832a25f403c43865c00bd072fa58b2da66bc8...  Ransomware
2776  RedLineStealer_26b9aeef55ded30a8664c048fa33795...  Ransomware
2460                             UpdateInformation.html  Ransomware
876   Dharma_e4a43f0bb8216496b95826c2c1aeb2f3ece6a7d...  Ransomware
1012  MedusaLocker_54b8ca90cd5c6b8053a612d2e8d99bf05...  Ransomware
1070  NominatusStorm_6b0e932c0ffbf5def120c877796af83...  Ransomware
2891  WannaCry_ad55f0db99cb7b4cc2189bb0434d6002f8bd2...  Ransomware
2017  None_05e849afaf9291fb32caff88ea535c103660aa028...  Ransomware
702   WastedLocker_0e061255b12ade5dc10f4ad9aeca9ebe5...  Ransomware
1265                          Wannacry_smb-3kn32w1v.bin  Ransomware
799   Blackcocaine_87f1bbfe76d7dfd6d0e2c15caf4343090...  Ransomware
593   Snatch_c64bf1a1e4d47232d1966ec0515f7d80503a001...  Ransomware
738   AvosLocker_5d6e4bd7bd7239fab20e043fb2929744972...  Ransomware
2630                               AttachedForm682.html  Ransomware
1884  Hive_ef29e4b32e6de86c5892e2f6d9e1029a49aef2832...  Ransomware
2621                                  FormAttached.html  Ransomware
395   Wintenzz_1ba9ef8703b10a0f158636a138b120835e958...  Ransomware
1567  Azov_aae8f441367e5b86a5f46bfd062c42886c6df0cff...  Ransomware
2165  None_a6f33427a356dca0420466bcc3283592e87caf4c8...  Ransomware
909   FireCrypt_890970d48e9a0c326a781d188b6c123f8448...  Ransomware
645   Vovalex_e9ee500bcceeb9608800148f7c750e5d8676fb...  Ransomware
1150  Ransomware_7e0ee0e707db426eaf25bd0924631db969b...  Ransomware
2146  None_9c267d6fa78174b3cba8ac8de558d83a97efb8494...  Ransomware
541   Nemty_9093233af919545a06bb718dd45e2b033be1caaf...  Ransomware
2803  RedLineStealer_f2c0e5c2636714a5952c64adf4df183...  Ransomware
1565  Azov_a4a6ee276fc98d6735f34c917bdfbbf5c7d4b955e...  Ransomware
2221  None_dbf3ca4534f5cf0866e5e03c22475df6ed90efb88...  Ransomware
1803  GandCrab_a70857f3f591969f3797e6704e3bfda9b1276...  Ransomware
703   WastedLocker_db665f26dbc4ca92d326f2cb98faafb9e...  Ransomware
1681  DarkSide_2d82be244e23001148ed5a6d83856b6f7cd20...  Ransomware
475   ESCAL_0f530bcb62462d9a7eed100bca3072f9df682f57...  Ransomware
2393                             UpdateInformation.html  Ransomware
2177  None_b425fcfcab98d57a198166faa21768b84e6ab8c75...  Ransomware
2147  None_98a09f7896a7c20229e696d6e8344fe9593fd70af...  Ransomware
1619  Chaos_61f2968848a1e7d26561fdd14e06b49424418e56...  Ransomware
2528                                     Update474.html  Ransomware
2148  None_9ad63be89938c8fc3a1bd9aa99d02b524e90b6927...  Ransomware
681   CobaltStrike_0c71dcca7d39fd895a7b772ccd2370fc9...  Ransomware
762   Babuk_51c86805e6350412f78a21f197aa00b4c9d44841...  Ransomware
502   Makop_94658982002db6acea22c68b7619f71154933eff...  Ransomware
623   Thanos_1d4db8733c5f11ee8fca530aeb4a91069de04b1...  Ransomware
398   Zeoticus_c373d37b5a9427a18dbf93d519968d9fda04f...  Ransomware
2739                                    FormUpdate.html  Ransomware
1695  DarkSide_bafa2efff234303166d663f967037dae43701...  Ransomware
1009  Maui_45d8ac1ac692d6bb0fe776620371fca02b60cac8d...  Ransomware
924   GandCrab_56371497c7c6601a092fc76d226d70cf56a34...  Ransomware
921   GandCrab_8eb6541e1cbc27a2445bb66b6a1020c364750...  Ransomware
1966  NominatusStorm_5e36777ffee4ecd9acf82bfdcd5b2d4...  Ransomware
1980  NominatusStorm_921163ad4071cab6d00d03eb128294d...  Ransomware
1038  Makop_7b367f4c26ea8c16697cd8b2d41e568a1fa3a6a7...  Ransomware
2345                             UpdateInformation.html  Ransomware
2795  RedLineStealer_d17262e3d32fd6598a5112e636397a6...  Ransomware
898   EternityStealer_55bf0aa9c3d746b8e47635c2eae2ac...  Ransomware
7     Balaclava_b8d026c281a072f68ee72d801f83df068cf0...  Ransomware
1929  Nitro_4fba7e65f6562871a003aca98b980a3deaade6e7...  Ransomware
1908  Magniber_5f6504ad8deff20cae43dec0312540b3cb221...  Ransomware
1774  GandCrab_796d802e56c0c31247611b3d76e6192c77f41...  Ransomware
1710  Dharma_307077d1a3fd2b53b94d88268e31b0b89b8c0c2...  Ransomware
1001  Magniber_79494b2b76515207a2cf1a29484096cbf884e...  Ransomware
754   Babuk_1b9412ca5e9deb29aeaa37be05ae8d0a8a636c12...  Ransomware
945   Hermes_448967673eb39db15958137b7563ba9dc6a321f...  Ransomware
1214  Stop_b9aaf852417503d7ff055b60e91d326743e7f0e22...  Ransomware
2063  None_32b1315bd48b4f49ccd3303f5fcf7d16b5c66c252...  Ransomware
14    Babuk_ab4eae618bb05b4fb4a8d3790a0d18a3e1566ab4...  Ransomware
2910  Zeppelin_7757c11c449860e2dd54ae97e05835fb39f89...  Ransomware
687   LegionLocker_bc016ebc1751fe99de886be19c2c3e0ba...  Ransomware
58    Crypt888_faa47da24f0494f637c0264a6d1d53f033a69...  Ransomware
497   HelloKitty_9a7daafc56300bd94ceef23eac56a0735b6...  Ransomware
763   Babuk_58ccba4fb2b3ed8b5f92adddd6ee331a6afdedfc...  Ransomware
2555                                 UpdateRecords.html  Ransomware
534   MountLocker_187610fb06cc60c73c0062b593c5fe3ba2...  Ransomware

In [ ]:
for index in adv_idx: 
    print(int(index))

1624
390
112
2021
1268
1976
1744
2149
32
1586

In [ ]:
mask = np.ones(X_train.shape[0], dtype=bool)
mask[adv_idx] = False

X_train = X_train[mask]
y_train = y_train[mask]

print(len(X_train))

1992

In [ ]:
k = 100
remove_samples_from_asamples = random.sample(asamples, k)
print(len(remove_samples_from_asamples))

100

In [ ]:
result = [item for item in asamples if item not in remove_samples_from_asamples]
np_result = np.array(result)
print(len(result))
poisoned_xtrain = np.concatenate((X_train, np_result))
len(poisoned_xtrain)

159

2151

In [ ]:
len(y_train)

1992

In [ ]:
adv_y = []
for i in range(len(np_result)): 
    adv_y.append(1) 
    
print(len(adv_y))

np_advy = np.array(adv_y)
poisoned_ytrain = np.concatenate((y_train, np_advy))
print(len(poisoned_ytrain))

159
2151

In [ ]:
poisoned_classifier = RandomForestClassifier(n_estimators=100, random_state=41)
poisoned_classifier.fit(poisoned_xtrain, poisoned_ytrain)
y_pred_poisoned = poisoned_classifier.predict(X_test)
poisoned_accuracy = accuracy_score(y_test, y_pred_poisoned)
print(f'Accuracy trained on poisoned samples: {poisoned_accuracy * 100:.2f}%')
cm_poisoned = confusion_matrix(y_test, y_pred_poisoned)
print(f"Confusion Matrix trained on poisoned samples:\n {cm_poisoned}") 
cr_poisoned = classification_report(y_test, y_pred_poisoned)
print(f"Classification report trained on poisoned samples:\n {cr_poisoned}")

Accuracy trained on poisoned samples: 97.60%
Confusion Matrix trained on poisoned samples:
 [[104  13]
 [  1 465]]
Classification report trained on poisoned samples:
               precision    recall  f1-score   support

           0       0.99      0.89      0.94       117
           1       0.97      1.00      0.99       466

    accuracy                           0.98       583
   macro avg       0.98      0.94      0.96       583
weighted avg       0.98      0.98      0.98       583

In [ ]:
def make_pred_poisoned(samples):
    predictions = [] 
    for sample in samples:
        single_pred = poisoned_classifier.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("Adversarial sample still adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        one_counter+=1 
        
    
    print(f"Samples still adversarial: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned(remove_samples_from_asamples)

[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
Samples still adversarial: 0
adversarial_samples identified: 100

In [ ]:
###Model transfer ###
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [ ]:
X = data.iloc[:, 2:-1].values
y = data.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred_clf = clf.predict(X_test)
accuracy_clf = accuracy_score(y_test, y_pred_clf)
print(f'Accuracy: {accuracy_clf * 100:.2f}%')

Accuracy: 97.08%

In [ ]:
def make_pred_poisoned_dt(samples):
    predictions = [] 
    for sample in samples:
        single_pred = clf.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("Adversarial sample still adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        else:
            one_counter+=1 
        
    
    print(f"adversarial Samples successful: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned_dt(asamples)

[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[0]
Adversarial sample still adversarial
adversarial Samples successful: 257
adversarial_samples identified: 81

In [ ]:
params = {
    'objective':'binary:logistic',
    'max_depth':4,
    'learning_rate':0.1,
    'n_estimators':10,
    'alpha':10
}

model = XGBClassifier(**params)
model.fit(X_train, y_train)
y_pred_xgb = model.predict(X_test)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f'Accuracy: {accuracy_xgb * 100:.2f}%')

Accuracy: 97.60%

In [ ]:
def make_pred_poisoned_XGB(samples):
    predictions = [] 
    for sample in samples:
        single_pred = model.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("Adversarial sample still adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        else:
            one_counter+=1 
        
    
    print(f"Samples still adversarial: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned_XGB(asamples)

[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
Samples still adversarial: 0
adversarial_samples identified: 338

In [ ]:
svm_classifier = SVC(kernel='poly', C=1.0, random_state=42)
svm_classifier.fit(X_train, y_train)
y_pred = svm_classifier.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")

Accuracy: 0.80

In [ ]:
def make_pred_poisoned_SVM(samples):
    predictions = [] 
    for sample in samples:
        single_pred = svm_classifier.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("sample adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        else:
            one_counter+=1 
        
    
    print(f"Samples still adversarial: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned_SVM(asamples)

[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
Samples still adversarial: 0
adversarial_samples identified: 338

In [ ]:
LR_model = LogisticRegression(solver='saga',max_iter=5000)
LR_model.fit(X_train, y_train)
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.8

c:\Users\Neezy\anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [ ]:
def make_pred_poisoned_LR(samples):
    predictions = [] 
    for sample in samples:
        single_pred = LR_model.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("Adversarial sample still adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        else:
            one_counter+=1 
        
    
    print(f"Samples still adversarial: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned_LR(asamples)

[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[0]
Adversarial sample still adversarial
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
Samples still adversarial: 5
adversarial_samples identified: 333